name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.1.0,<0.2.0
  - pip:
    - jupyterlite-xeus>=0.1.2,<0.2
    - jupyterlab-filesystem-access
    - jupyterlab-webrtc-docprovider
    - fsspec
    - matplotlib
    - ipympl
    - pandas
    - numpy
    - basemap
    - boto3
    - seaborn
