name: my-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - ipympl
  - basemap
